name: Build and Deploy on AWS

on:
  pull_request:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  API_URL: ${{ secrets.API_URL }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

     - name: create env file
      run: |
        touch .env
        echo API_URL =${{ secrets.API_URL }} >> .env