name: 02 - Secret Workflow

on:
  schedule:
    - cron: '0 1 * * *' # Runs at 01:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Commands with Secret
        env:
          API_URL: ${{ secrets.API_URL }}
